### ISSUE TITLE
Player not Found

### ISSUE THREAD

**Issue by CheatCoder** [weaondara/BungeePerms#158]
Version:
````
09:55:39 [INFO] Welcome to BungeePerms, a BungeeCord permissions plugin
09:55:39 [INFO] Version 3.0-alpha-1
09:55:39 [INFO] Author wea_ondara
````

Error:
````
[09:45:31 INFO]: UUID of player Kotarou is 2f230c47-c976-4ca9-a32a-9187b452a961
[09:45:31 INFO]: [null] [Debug] User Kotarou not found!!!
[09:45:31 INFO]: Kotarou[/109.43.0.241:56443] logged in with entity id 361 at ([world]205.5078919896623, 71.0, 253.30000001192093)
````
So i think that there is a mistake configuration.

Bungeecord Config:
```yaml  
  useUUIDs: true
    useregexperms: true
    grouppermission: true
   backendtype: MySQL2
   uuidplayerdb: MySQL
   tablePrefix: bungeeperms_
   uuidfetcher:
   cooldown: 3000
   saveAllUsers: true
    deleteUsersOnCleanup: false
    notify:
    promote: false
   demote: false
   tabcomplete: true
   locale: en-GB
   networktype: Global
   networkservers: []
   debug:
     path: plugins/BungeePermsBukkit/debug.log
     showexceptions: true
     showlogs: true
   bungeeperms:
    general:
       mysqlhost: localhost
       mysqlport: '3306'
       mysqldb: minecraft
       mysqluser: minecraft
       mysqlpw: Removed
    terminate:
     prefix:
       reset: true
       space: true
     suffix:
       reset: true
       space: true
     cleanup:
       interval: 1800
       threshold: 600
````

BungeePermsBukkit Config:

```yaml
servername: lobby
debug:
  path: plugins/BungeePermsBukkit/debug.log
  showexceptions: true
  showlogs: true
backendtype: MySQL2
useUUIDs: true
uuidplayerdb: MySQL
tablePrefix: bungeeperms_
bungeeperms:
  general:
    mysqlhost: localhost
    mysqlport: '3306'
    mysqldb: minecraft
    mysqluser: minecraft
    mysqlpw: Removed
allowops: true
useregexperms: true
superpermscompat: false
````

I hope you can help then i can't execute /gm or other commands.

Thankfully,

CheatCoder
