### ISSUE TITLE
Inheritance not recursive

### ISSUE THREAD

**Issue by CTMiner** [weaondara/BungeePerms#20]
My permission inheritances aren't re-cursing. My config is as follows:

```
groups:
  guest:
    inheritances: []
    permissions:
    - ct.bungee.ranks.main.guest
    - bungeecord.command.server
    - bungeecord.command.list
    - bungeecord.command.find
    rank: 1500
    ladder: default
    default: true
    display: ''
    prefix: ''
    suffix: ''
  registered:
    inheritances: []
    permissions:
    - ct.bungee.ranks.main.registered
    - bungeecord.command.server
    - bungeecord.command.list
    - bungeecord.command.find
    rank: 1500
    ladder: default
    default: true
    display: ''
    prefix: ''
    suffix: ''
  donator:
    inheritances:
    - registered
    permissions:
    - ct.bungee.ranks.donator.donator
    rank: 1500
    ladder: default
    default: false
    display: ''
    prefix: ''
    suffix: ''
  premium:
    inheritances:
    - donator
    permissions:
    - ct.bungee.ranks.donator.premium
    rank: 1500
    ladder: default
    default: false
    display: ''
    prefix: ''
    suffix: ''
  elite:
    inheritances:
    - premium
    permissions:
    - ct.bungee.ranks.donator.elite
    rank: 1500
    ladder: default
    default: false
    display: ''
    prefix: ''
    suffix: ''
  mod:
    inheritances:
    - registered
    permissions:
    - ct.bungee.ranks.staff.mod
    rank: 1500
    ladder: default
    default: false
    display: ''
    prefix: ''
    suffix: ''
  admin:
    inheritances:
    - mod
    permissions:
    - ct.bungee.ranks.staff.admin
    - bungeecord.command.alert
    - bungeecord.command.ip
    - bungeecord.command.send
    - bungeefilter.reload
    - bungeeperms.groups
    - bungeeperms.group.info
    - bungeeperms.group.perms.has
    - bungeeperms.group.perms.list
    - bungeeperms.help
    - bungeeperms.reload
    - bungeeperms.users
    - bungeeperms.user.info
    - bungeeperms.user.perms.has
    - bungeeperms.user.perms.list
    - bungeesuite.reload
    - ct.bungee.tp.tp
    - ct.bungee.tp.tphere
    rank: 1500
    ladder: default
    default: false
    display: ''
    prefix: ''
    suffix: ''
  dev:
    inheritances:
    - registered
    permissions:
    - ct.bungee.ranks.other.dev
    rank: 1500
    ladder: default
    default: false
    display: ''
    prefix: ''
    suffix: ''
  originalmember:
    inheritances:
    - registered
    permissions:
    - ct.bungee.ranks.other.originalmember
    rank: 1500
    ladder: default
    default: false
    display: ''
    prefix: ''
    suffix: ''
  internetfamous:
    inheritances:
    - registered
    permissions:
    - ct.bungee.ranks.other.internetfamous
    rank: 1500
    ladder: default
    default: false
    display: ''
    prefix: ''
    suffix: ''
  owner:
    inheritances:
    - admin
    permissions:
    - ct.bungee.ranks.staff.owner
    - bungeeperms.*
    rank: 1500
    ladder: default
    default: false
    display: ''
    prefix: ''
    suffix: ''
version: 1
users:
  CTMiner:
    groups:
    - owner
    permissions:
    - bungeeperms.*
```

Here is the output of a /bp user CTMiner list:

```
3:36:47 [INFO] §7Permissions of the player §3CTMiner§7:
23:36:47 [INFO] §7- §6ct.bungee.ranks.staff.admin
23:36:47 [INFO] §7- §6bungeecord.command.alert
23:36:47 [INFO] §7- §6bungeecord.command.ip
23:36:47 [INFO] §7- §6bungeecord.command.send
23:36:47 [INFO] §7- §6bungeefilter.reload
23:36:47 [INFO] §7- §6bungeeperms.groups
23:36:47 [INFO] §7- §6bungeeperms.group.info
23:36:47 [INFO] §7- §6bungeeperms.group.perms.has
23:36:47 [INFO] §7- §6bungeeperms.group.perms.list
23:36:47 [INFO] §7- §6bungeeperms.help
23:36:47 [INFO] §7- §6bungeeperms.reload
23:36:47 [INFO] §7- §6bungeeperms.users
23:36:47 [INFO] §7- §6bungeeperms.user.info
23:36:47 [INFO] §7- §6bungeeperms.user.perms.has
23:36:47 [INFO] §7- §6bungeeperms.user.perms.list
23:36:47 [INFO] §7- §6bungeesuite.reload
23:36:47 [INFO] §7- §6ct.bungee.tp.tp
23:36:47 [INFO] §7- §6ct.bungee.tp.tphere
23:36:47 [INFO] §7- §6ct.bungee.ranks.staff.owner
23:36:47 [INFO] §7- §6bungeeperms.*
```

Thanks in advance for any help you can give - CT
