### ISSUE TITLE
is the mysql config still correct

### ISSUE THREAD

**Issue by braddevans** [weaondara/BungeePerms#341]
is this still correct from the last time the wiki was updated
```yaml
bungeeperms:
    general:
        mysqlhost: localhost
        mysqlport: '3306'
        mysqldb: database
        mysqluser: mysqluser
        mysqlpw: password
```
