### ISSUE TITLE
Apply permissions by specifying multiple servers at once

### ISSUE THREAD

**Issue by dalbodeule** [weaondara/BungeePerms#365]
This time, I have created a large enough content that I have to divide a server of one content into several for optimization. I used BungeePerms at this point, and I felt a little uncomfortable using it.

In case of BungeePerms, because it is linked with BungeeCord, it is designed to specify permission for each server and each world unlike other Permission Plugin. The problem is in specifying the server name.

As described above, when one content is divided into several servers and then interlocked, the same permission may need to be applied to multiple servers. However, BungeePerms automatically updates the servername field in Config, so to apply the same permission to multiple servers, you must write a permission rule for each server as follows:

```yaml
    server:
        rpg_field:
            permissions:
            - a.a
        rpg_town:
            permissions:
            - a.a
```

I would at least wish to have something efficient like this when writing server-specific permissions:

```yaml
    server:
        rpg_(?:field|town):
            permissions:
            - a.a
```

I used a translator because I am not good at English. There may be an error.
